import { NextRequest, NextResponse } from 'next/server'
import prisma from '@/lib/prisma'
import { gatherReportData } from '@/lib/report/reportData'
import { generateReportHtml, type LLMNarratives } from '@/lib/report/reportTemplate'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import path from 'path'

const REPORT_OUTPUT_PATH = process.env.REPORT_OUTPUT_PATH || '/data/reports'
const AGENT_API_URL = process.env.AGENT_API_URL || 'http://agent:8080'

interface RouteParams {
  params: Promise<{ id: string }>
}

/** 生成中文报告标题，供数据库元数据和前端列表展示。 */
function buildReportTitle(projectName: string): string {
  return `渗透测试报告 - ${projectName}`
}

/** 将模板生成的固定英文 HTML 文案替换为中文，避免改动模板文件即可输出中文报告。 */
function localizeReportHtml(html: string): string {
  const replacements: Array<[string, string]> = [
    ['<html lang="en">', '<html lang="zh-CN">'],
    ['Penetration Test Report', '渗透测试报告'],
    ['Table of Contents', '目录'],
    ['Executive Summary', '执行摘要'],
    ['Scope &amp; Methodology', '测试范围与方法'],
    ['Risk Summary', '风险概览'],
    ['Other Vulnerability Details', '其他漏洞详情'],
    ['Attack Surface', '攻击面'],
    ['CVE Intelligence', 'CVE 情报'],
    ['GitHub Secrets', 'GitHub 密钥泄露'],
    ['TruffleHog Findings', 'TruffleHog 发现'],
    ['Secret Detection', '密钥检测'],
    ['JavaScript Reconnaissance', 'JavaScript 侦察'],
    ['GraphQL Security', 'GraphQL 安全'],
    ['VHost &amp; SNI Enumeration', 'VHost 与 SNI 枚举'],
    ['AI Surface', 'AI 攻击面'],
    ['OTX Threat Intelligence', 'OTX 威胁情报'],
    ['Attack Chains', '攻击链'],
    ['Recommendations', '修复建议'],
    ['Appendix', '附录'],
    ['Date', '日期'],
    ['Client Contact', '客户联系人'],
    ['Client', '客户'],
    ['Engagement Type', '测试类型'],
    ['Start Date', '开始日期'],
    ['End Date', '结束日期'],
    ['Risk Score', '风险评分'],
    ['Classification', '密级'],
    ['CONFIDENTIAL', '机密'],
    ['Total Findings', '发现总数'],
    ['Confirmed Exploits', '已确认利用'],
    ['Avg CVSS', '平均 CVSS'],
    ['Remediations', '修复项'],
    ['Secrets Exposed', '泄露密钥'],
    ['Critical', '严重'],
    ['High', '高危'],
    ['Medium', '中危'],
    ['Low', '低危'],
    ['Scan Mode', '扫描模式'],
    ['Subdomains', '子域名'],
    ['Unique IPs', '唯一 IP 数'],
    ['Base URLs', '基础 URL'],
    ['Endpoints', '端点'],
    ['Parameters', '参数'],
    ['Verified', '已验证'],
    ['Repositories', '仓库数'],
    ['Threat Pulses', '威胁脉冲'],
    ['Malware Samples', '恶意软件样本'],
    ['Enriched IPs', '已富化 IP'],
    ['Threat Actors', '威胁行为体'],
    ['Findings Detail', '发现详情'],
    ['Findings', '发现项'],
    ['Generated by RedAmon on', '由 RedAmon 生成于'],
    ['This document contains confidential security assessment results. Handle according to classification.', '本文档包含机密的安全评估结果，请按密级要求进行处理。'],
  ]

  return replacements.reduce(
    (localizedHtml, [from, to]) => localizedHtml.replaceAll(from, to),
    html,
  )
}

/** GET /api/projects/{id}/reports — List all reports for a project */
export async function GET(_request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params
    const reports = await prisma.report.findMany({
      where: { projectId: id },
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        title: true,
        filename: true,
        fileSize: true,
        format: true,
        metrics: true,
        hasNarratives: true,
        createdAt: true,
      },
    })
    return NextResponse.json(reports)
  } catch (error) {
    console.error('List reports failed:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to list reports' },
      { status: 500 }
    )
  }
}

/** POST /api/projects/{id}/reports — Generate a new report */
export async function POST(_request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params

    // 1. Gather all data from Neo4j + PostgreSQL
    const reportData = await gatherReportData(id)

    // 2. Request LLM narratives from the agent service (with fallback)
    let narratives: LLMNarratives | null = null
    try {
      const condensed = condenseForAgent(reportData)
      const resp = await fetch(`${AGENT_API_URL}/api/report/summarize`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ data: condensed }),
        signal: AbortSignal.timeout(300_000), // 5 min timeout
      })
      if (resp.ok) {
        narratives = await resp.json() as LLMNarratives
      } else {
        console.warn(`Report narratives failed (${resp.status}): ${await resp.text()}`)
      }
    } catch (err) {
      console.warn('Agent unavailable for report narratives, generating without:', err)
    }

    // 3. Generate HTML
    const html = localizeReportHtml(generateReportHtml(reportData, narratives))

    // 4. Write to disk
    if (!existsSync(REPORT_OUTPUT_PATH)) {
      mkdirSync(REPORT_OUTPUT_PATH, { recursive: true })
    }
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19)
    const safeName = reportData.project.name.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 40)
    const filename = `report_${safeName}_${timestamp}.html`
    const filePath = path.join(REPORT_OUTPUT_PATH, filename)
    const htmlBuffer = Buffer.from(html, 'utf-8')
    writeFileSync(filePath, htmlBuffer)

    // 5. Save metadata to DB
    const report = await prisma.report.create({
      data: {
        projectId: id,
        title: buildReportTitle(reportData.project.targetDomain || reportData.project.name),
        filename,
        filePath,
        fileSize: htmlBuffer.length,
        format: 'html',
        hasNarratives: narratives !== null,
        metrics: {
          riskScore: reportData.metrics.riskScore,
          riskLabel: reportData.metrics.riskLabel,
          totalVulnerabilities: reportData.metrics.totalVulnerabilities,
          totalCves: reportData.metrics.totalCves,
          criticalCount: reportData.metrics.criticalCount,
          highCount: reportData.metrics.highCount,
          mediumCount: reportData.metrics.mediumCount,
          lowCount: reportData.metrics.lowCount,
          cveCriticalCount: reportData.metrics.cveCriticalCount,
          cveHighCount: reportData.metrics.cveHighCount,
          cveMediumCount: reportData.metrics.cveMediumCount,
          cveLowCount: reportData.metrics.cveLowCount,
          totalRemediations: reportData.metrics.totalRemediations,
          exploitableCount: reportData.metrics.exploitableCount,
        },
      },
    })

    return NextResponse.json(report, { status: 201 })
  } catch (error) {
    console.error('Generate report failed:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Report generation failed' },
      { status: 500 }
    )
  }
}

/** Condense ReportData into a smaller payload for the LLM summarizer.
 *  Sends ALL CVEs, findings, exploits, and remediations so the LLM can
 *  produce a comprehensive triage in the recommendations section. */
function condenseForAgent(data: ReturnType<typeof gatherReportData> extends Promise<infer T> ? T : never) {
  // Deduplicate ALL CVE chains by CVE ID
  const seenCves = new Set<string>()
  const allChains = data.cveIntelligence.cveChains
    .filter(c => {
      if (!c.cveId || seenCves.has(c.cveId)) return false
      seenCves.add(c.cveId)
      return true
    })
    .map(c => ({
      tech: c.tech, techVersion: c.techVersion,
      cveId: c.cveId, cvss: c.cvss, cveSeverity: c.cveSeverity,
      cweId: c.cweId, cweName: c.cweName,
      capecId: c.capecId, capecName: c.capecName,
    }))

  return {
    project: {
      name: data.project.name,
      targetDomain: data.project.targetDomain,
      roeEngagementType: (data.project as any).roeEngagementType,
      roeClientName: (data.project as any).roeClientName,
    },
    metrics: data.metrics,
    graphOverview: {
      totalNodes: data.graphOverview.totalNodes,
      subdomainStats: data.graphOverview.subdomainStats,
      endpointCoverage: data.graphOverview.endpointCoverage,
      certificateHealth: data.graphOverview.certificateHealth,
      infrastructureStats: data.graphOverview.infrastructureStats,
    },
    attackSurface: {
      technologies: data.attackSurface.technologies,
      services: data.attackSurface.services,
      ports: data.attackSurface.ports,
      securityHeaders: data.attackSurface.securityHeaders,
      parameterAnalysis: data.attackSurface.parameterAnalysis,
    },
    vulnerabilities: {
      severityDistribution: data.vulnerabilities.severityDistribution,
      cvssHistogram: data.vulnerabilities.cvssHistogram,
      findings: data.vulnerabilities.findings.map(f => ({
        name: f.name,
        severity: f.severity,
        findingSource: f.findingSource,
        target: f.target || f.host,
        category: f.category,
        cvssScore: f.cvssScore,
      })),
    },
    cveIntelligence: {
      exploits: data.cveIntelligence.exploits.map(e => ({
        name: e.name,
        cvssScore: e.cvssScore,
        cveIds: e.cveIds,
        cisaKev: e.cisaKev,
        targetIp: e.targetIp,
      })),
      githubSecrets: data.cveIntelligence.githubSecrets,
      cveChains: allChains,
    },
    attackChains: {
      chains: data.attackChains.chains,
      exploitSuccesses: data.attackChains.exploitSuccesses.map(e => ({
        title: e.title,
        targetIp: e.targetIp,
        attackType: e.attackType,
        cveIds: e.cveIds,
        module: e.module,
        evidence: e.evidence,
      })),
    },
    remediations: data.remediations.map(r => ({
      title: r.title,
      severity: r.severity,
      category: r.category,
      solution: r.solution,
      cveIds: r.cveIds,
      cweIds: r.cweIds,
      exploitAvailable: r.exploitAvailable,
      cisaKev: r.cisaKev,
      status: r.status,
      cvssScore: r.cvssScore,
      affectedAssets: r.affectedAssets,
    })),
    trufflehog: {
      totalFindings: data.trufflehog.totalFindings,
      verifiedFindings: data.trufflehog.verifiedFindings,
      repositories: data.trufflehog.repositories,
      findings: data.trufflehog.findings.slice(0, 20).map(f => ({
        detectorName: f.detectorName,
        verified: f.verified,
        repository: f.repository,
        file: f.file,
      })),
    },
    secrets: {
      total: data.secrets.total,
      bySeverity: data.secrets.bySeverity,
      bySource: data.secrets.bySource,
      byType: data.secrets.byType,
    },
    jsRecon: {
      totalFindings: data.jsRecon.totalFindings,
      bySeverity: data.jsRecon.bySeverity,
      byType: data.jsRecon.byType,
      findings: data.jsRecon.findings.slice(0, 20).map(f => ({
        title: f.title,
        severity: f.severity,
        findingType: f.findingType,
        confidence: f.confidence,
      })),
    },
    graphqlScan: {
      totalFindings: data.graphqlScan.totalFindings,
      endpointsTested: data.graphqlScan.endpointsTested,
      introspectionEnabled: data.graphqlScan.introspectionEnabled,
      bySeverity: data.graphqlScan.bySeverity,
      byType: data.graphqlScan.byType,
      topFindings: data.graphqlScan.findings.slice(0, 15).map(f => ({
        title: f.title,
        severity: f.severity,
        vulnerabilityType: f.vulnerabilityType,
        source: f.source,   // 'graphql_scan' vs 'graphql_cop' — helps LLM narrate differently
        endpoint: f.endpoint,
      })),
    },
    vhostSni: {
      totalFindings: data.vhostSni.totalFindings,
      ipsTested: data.vhostSni.ipsTested,
      anomaliesL7: data.vhostSni.anomaliesL7,
      anomaliesL4: data.vhostSni.anomaliesL4,
      reverseProxiesDetected: data.vhostSni.reverseProxiesDetected,
      bySeverity: data.vhostSni.bySeverity,
      byLayer: data.vhostSni.byLayer,
      byType: data.vhostSni.byType,
      topFindings: data.vhostSni.findings.slice(0, 15).map(f => ({
        hostname: f.hostname,
        severity: f.severity,
        layer: f.layer,
        type: f.type,
        target: f.ip ? `${f.ip}${f.port ? ':' + f.port : ''}` : null,
        internalPatternMatch: f.internalPatternMatch,
      })),
    },
    aiSurface: {
      totalAiEndpoints: data.aiSurface.totalAiEndpoints,
      ragIngestEndpoints: data.aiSurface.ragIngestEndpoints,
      promptInjectableParams: data.aiSurface.promptInjectableParams,
      mcpServers: data.aiSurface.mcpServers,
      mcpPoisoningFindings: data.aiSurface.mcpPoisoningFindings,
      vectorDbs: data.aiSurface.vectorDbs,
      modelFamilies: data.aiSurface.modelFamilies,
      byInterfaceType: data.aiSurface.byInterfaceType,
      // Top 15 endpoints for the LLM's narrative (full 50 stay in the HTML report)
      sampleEndpoints: data.aiSurface.findings.slice(0, 15).map(f => ({
        baseUrl: f.baseUrl,
        path: f.path,
        interfaceType: f.interfaceType,
        isRagIngest: f.isRagIngest,
        promptInjectableParams: f.promptInjectableParams,
      })),
    },
    otx: {
      totalPulses: data.otx.totalPulses,
      totalMalware: data.otx.totalMalware,
      enrichedIps: data.otx.enrichedIps,
      adversaries: data.otx.adversaries,
      pulses: data.otx.pulses.slice(0, 15).map(p => ({
        name: p.name,
        adversary: p.adversary,
        malwareFamilies: p.malwareFamilies,
        attackIds: p.attackIds,
      })),
    },
  }
}
